title: PoolParty User Documentation By The Cultural Heritage Agency Of The Netherlands
description: A guide for users on how to start working with PoolParty and managing a Thesaurus.
theme: just-the-docs
baseurl: /Poolparty-User-Documentation
url: https://cultureelerfgoed.github.io

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

exclude:
  # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:

  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md





