title: PoolParty User Documentation By The Cultural Heritage Agency Of The Netherlands
description: A guide for users on how to start working with PoolParty and managing a Thesaurus.
theme: just-the-docs
baseurl: /Poolparty-User-Documentation
url: https://cultureelerfgoed.github.io

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

exclude:
  # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:

  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md

callouts:
  important:
    title: Belangrijk
    color: blue
    text-tranform: none

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase


# new
markdown: kramdown

# _config.yml
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    disable: true
  parse_block_html: true
  parse_span_html: true
  html_to_native: true

safe: true

